[build]
  base = "ufogram"
  publish = "build"
  command = "npm install --legacy-peer-deps && DISABLE_ESLINT_PLUGIN=true npm run build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.10.0"